version: 0

type: "single"
worker:
  container: "tensorflow/tensorflow:1.8.0-gpu"
  command: "python3 src/generate_unconditional_samples.py | tee /artifacts/samples.log"
  machine-type: "P5000"
  dockerfile: https://github.com/tallyw00d/gpt-2/blob/finetuning/Dockerfile.gpu
    use: true
    path: "./docker/worker-Dockerfile"
